### ISSUE TITLE
Tracebacks on auth now

### ISSUE THREAD

**Issue by alsparks** [thevalyreangroup/node-red-contrib-ringdoorbell#9]
Starting on December 18, I've been getting the following sort of authentication tracebacks on my Ring flows.  Did Ring change authentication and break this node?  I do NOT have 2FA enabled at this time.
-Alan

Dec 22 12:05:23 neptune node-red[27955]:   ownMessage:
Dec 22 12:05:23 neptune node-red[27955]:    'ring gave a seemingly valid authentication/authorisation, but the failed',
Dec 22 12:05:23 neptune node-red[27955]:   causedBy:
Dec 22 12:05:23 neptune node-red[27955]:    { Error: problem GETing endpoint https://api.ring.com/clients_api/ring_devices --caused-by-> Request to ring API at https://api.ring.com/clients_api/ring_devices failed with "not authorized" --caused-by-> Request failed with status code 401
Dec 22 12:05:23 neptune node-red[27955]:        at module.exports (/home/node-red/.node-red/node_modules/ring-api/propagated-error.js:22:19)
Dec 22 12:05:23 neptune node-red[27955]:        at Object.authenticatedRequest (/home/node-red/.node-red/node_modules/ring-api/rest-client.js:166:23)
Dec 22 12:05:23 neptune node-red[27955]:        at process._tickCallback (internal/process/next_tick.js:68:7)
Dec 22 12:05:23 neptune node-red[27955]:      ownMessage:
Dec 22 12:05:23 neptune node-red[27955]:       'problem GETing endpoint https://api.ring.com/clients_api/ring_devices',
Dec 22 12:05:23 neptune node-red[27955]:      causedBy:
Dec 22 12:05:23 neptune node-red[27955]:       { Error: Request to ring API at https://api.ring.com/clients_api/ring_devices failed with "not authorized" --caused-by-> Request failed with status code 401
Dec 22 12:05:23 neptune node-red[27955]:           at module.exports (/home/node-red/.node-red/node_modules/ring-api/propagated-error.js:22:19)
Dec 22 12:05:23 neptune node-red[27955]:           at ringRequest (/home/node-red/.node-red/node_modules/ring-api/rest-client.js:71:19)
Dec 22 12:05:23 neptune node-red[27955]:           at process._tickCallback (internal/process/next_tick.js:68:7)
Dec 22 12:05:23 neptune node-red[27955]:         ownMessage:
Dec 22 12:05:23 neptune node-red[27955]:          'Request to ring API at https://api.ring.com/clients_api/ring_devices failed with "not authorized"',
Dec 22 12:05:23 neptune node-red[27955]:         causedBy: [Error],
Dec 22 12:05:23 neptune node-red[27955]:         isPropagatedError: true },
Dec 22 12:05:23 neptune node-red[27955]:      isPropagatedError: true },
Dec 22 12:05:23 neptune node-red[27955]:   isPropagatedError: true }

**Comment by svaeyens** [comment]
Exactly the same issue here.

**Comment by TonySimons-TVG** [comment]
@alsparks As you've seen, I've largely abandoned this repo in the past couple years. I plan to revisit this in the next few weeks to get it operational again and add more features.

**Comment by alsparks** [comment]
Thanks.  Hope to see this alive again.

-Alan

**Comment by alsparks** [comment]
It's been a really long time.  Is there still any plan to get this working again?

**Comment by TonySimons-TVG** [comment]
@alsparks Yes, I still plan to. I just have not had time to do any major work on it yet.
